# Generated by Django 6.0.4 on 2026-04-16 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_marketitem_sitesettings_project_funding_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='funding_amount',
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='messages/'),
        ),
        migrations.AddField(
            model_name='message',
            name='msg_type',
            field=models.CharField(choices=[('text', 'Matn'), ('image', 'Rasm'), ('file', 'Fayl'), ('voice', 'Ovozli xabar')], default='text', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_collected',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name="Yig'ilgan summa"),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_goal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Maqsad qilingan summa'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('idea', "G'oya bosqichi"), ('funding', "Mablag' yig'ilmoqda (Crowdfunding)"), ('dev', 'Amalga oshirilmoqda (Development)'), ('active', 'Ishga tushirilgan (Launched)'), ('profit', 'Foydada (Profitable)'), ('failed', "Zararda/To'xtatilgan")], default='idea', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CallSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sig_type', models.CharField(choices=[('offer', 'Offer'), ('answer', 'Answer'), ('candidate', 'ICE Candidate'), ('call', 'Qongiroq'), ('accept', 'Qabul'), ('reject', 'Rad'), ('end', 'Tugatish')], max_length=15)),
                ('call_type', models.CharField(choices=[('video', 'Video'), ('audio', 'Ovoz')], default='video', max_length=10)),
                ('payload', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_signals', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_signals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
