name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "45.138.159.4"
          username: "host7905"
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 22
          timeout: 60s
          command_timeout: 10m
          script: |
            source /home/host7905/virtualenv/yoshiqtidorlar/3.11/bin/activate
            cd /home/host7905/yoshiqtidorlar
            git pull origin main
            pip install -r requirements.txt --quiet
            python manage.py makemigrations --noinput
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
            # Fayl huquqlari
            find . -type d -not -path './.git/*' -exec chmod 755 {} \;
            find . -type f -not -path './.git/*' -exec chmod 644 {} \;
            chmod 600 .env 2>/dev/null || true
            chmod 755 manage.py
            touch tmp/restart.txt
            echo "Deploy muvaffaqiyatli!"
