name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          timeout: 60s
          command_timeout: 10m
          script: |
            source /home/host7905/virtualenv/yoshiqtidorlar/3.11/bin/activate
            cd /home/host7905/yoshiqtidorlar
            git pull origin main
            pip install -r requirements.txt --quiet
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput
            touch tmp/restart.txt
            echo "✅ Deploy muvaffaqiyatli!"
